=== gotoeasy/gotoeasy-ioc/src/main/java/xsd/gotoeasy-beans.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.gotoeasy.top/schema/beans"
	targetNamespace="http://www.gotoeasy.top/schema/beans">

	<!-- IOC容器Bean配置格式定义 -->
	<xs:element name="beans">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<!-- beans标签包含 0~N个bean标签 -->
				<xs:element name="bean">
					<xs:complexType>
						<xs:sequence>
							<!-- bean标签包含 0~1个constructor构造方法标签，0个时通常不写 -->
							<xs:element name="constructor" minOccurs="0"
								maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<!-- bean标签包含 0~N个arg标签 -->
										<xs:element name="arg" minOccurs="0"
											maxOccurs="unbounded">
											<xs:complexType>
												<!-- 构造方法参数用的arg标签，arg标签顺序即构造方法参数顺序，value、ref两者必选一个进行设定，设定value时需指定class -->
												<xs:attribute name="value" type="xs:string" />
												<xs:attribute name="class" type="xs:string" />
												<xs:attribute name="ref" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>

							<!-- bean标签包含 0~N个property标签 -->
							<xs:element name="property" minOccurs="0"
								maxOccurs="unbounded">
								<xs:complexType>
									<!-- 用于注入的property标签，name必须设定，class+value、ref两者必选一个进行设定 -->
									<xs:attribute name="name" type="xs:string"
										use="required" />
									<xs:attribute name="class" type="xs:string" />
									<xs:attribute name="value" type="xs:string" />
									<xs:attribute name="ref" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>

						<!-- bean标签属性，id必须设定，class、class+value、ref三者必选一个进行设定 -->
						<xs:attribute name="id" type="xs:string"
							use="required" />
						<xs:attribute name="class" type="xs:string" />
						<xs:attribute name="value" type="xs:string" />
						<xs:attribute name="ref" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gotoeasy/gotoeasy-ioc/src/main/java/xsd/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<ioc:beans xmlns:ioc="http://www.gotoeasy.top/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.gotoeasy.top/schema/beans gotoeasy-beans.xsd">

	<!-- 按默认构造方法创建Bean -->
	<bean id="student" class="top.gotoeasy.sample.Student" />

	<!-- 简单类型 -->
	<bean id="age" class="int" value="20" />

	<!-- 单纯引用 -->
	<bean id="zhangsan" ref="student" />

	<!-- 按默认构造方法创建Bean，按指定属性注入 -->
	<bean id="lisi" class="top.gotoeasy.sample.Student">
		<property name="age" ref="age" />
		<property name="phone" value="13812345678" />
	</bean>

	<!-- 按指定构造方法创建Bean -->
	<bean id="wangwu" class="top.gotoeasy.sample.Student">
		<constructor>
			<arg ref="age" />
			<arg class="String" value="13812345678" />
		</constructor>
	</bean>

	<!-- 按指定构造方法创建Bean，按指定属性注入 -->
	<bean id="wangwu" class="top.gotoeasy.sample.Student">
		<constructor>
			<arg class="String" value="13812345678" />
		</constructor>
		<property name="age" ref="age" />
	</bean>

</ioc:beans>
